"""PostgreSQL contract for the financial-ratio natural-key repair.

The production `financial_ratios` table only ever got its primary-key index.
Without `uq_financial_ratio_symbol_period`, every
``INSERT ... ON CONFLICT (symbol, period, period_type)`` from
``get_upsert_stmt`` fails with
``there is no unique or exclusion constraint matching the ON CONFLICT specification``.
This contract runs the real migration against a disposable PostgreSQL schema and
asserts the natural-key upsert works, is idempotent, and keeps the newest row.
"""

from __future__ import annotations

import importlib.util
import os
from pathlib import Path
from uuid import uuid4

import pytest
from alembic.migration import MigrationContext
from alembic.operations import Operations
from sqlalchemy import create_engine, text


@pytest.mark.skipif(
    os.environ.get("POSTGRES_CONTRACT") != "1",
    reason="requires a disposable PostgreSQL contract database",
)
def test_financial_ratio_natural_key_migration_enables_upsert_without_loss():
    from conftest import postgres_contract_database_url

    migration_path = (
        Path(__file__).parents[2]
        / "migrations/versions/20261004_1700_restore_financial_ratio_natural_key.py"
    )
    spec = importlib.util.spec_from_file_location(
        "restore_financial_ratio_natural_key", migration_path
    )
    assert spec is not None and spec.loader is not None
    migration = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(migration)

    url = postgres_contract_database_url().replace("+asyncpg", "+psycopg2")
    engine = create_engine(url)
    schema = f"ratio_migration_{uuid4().hex}"

    upsert = text(
        """
        INSERT INTO financial_ratios (symbol, period, period_type, fiscal_year, pe_ratio)
        VALUES (:symbol, :period, :period_type, :fiscal_year, :pe_ratio)
        ON CONFLICT (symbol, period, period_type)
        DO UPDATE SET pe_ratio = EXCLUDED.pe_ratio, updated_at = now()
        """
    )

    try:
        with engine.connect() as conn:
            conn.execute(text(f"CREATE SCHEMA {schema}"))
            conn.commit()
            conn.execute(text(f"SET search_path TO {schema}"))
            conn.execute(
                text(
                    """
                    CREATE TABLE financial_ratios (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        symbol text NOT NULL,
                        period text NOT NULL,
                        period_type text NOT NULL,
                        fiscal_year integer NOT NULL,
                        pe_ratio double precision,
                        updated_at timestamptz NOT NULL DEFAULT now()
                    )
                    """
                )
            )
            # Drifted production shape: real rows, no natural-key constraint.
            conn.execute(
                text(
                    """
                    INSERT INTO financial_ratios (symbol, period, period_type, fiscal_year, pe_ratio)
                    VALUES ('VNM', '2026-Q2', 'quarter', 2026, 12.0),
                           ('VNM', '2026-Q1', 'quarter', 2026, 11.0)
                    """
                )
            )
            conn.commit()

            # Before the repair the ON CONFLICT write is rejected by Postgres.
            with pytest.raises(Exception) as failure:
                with conn.begin_nested():
                    conn.execute(
                        upsert,
                        {"symbol": "VNM", "period": "2026-Q2", "period_type": "quarter",
                         "fiscal_year": 2026, "pe_ratio": 13.0},
                    )
            assert "no unique or exclusion constraint" in str(failure.value)
            conn.rollback()

            context = MigrationContext.configure(conn)
            with Operations.context(context), context.begin_transaction():
                migration.upgrade()
            conn.commit()

            assert conn.scalar(
                text(
                    "SELECT count(*) FROM pg_constraint "
                    "WHERE conname = 'uq_financial_ratio_symbol_period' "
                    "AND conrelid = to_regclass('financial_ratios')"
                )
            ) == 1
            # Lossless: both real rows survive the constraint addition.
            assert conn.scalar(text("SELECT count(*) FROM financial_ratios")) == 2

            # The upsert now updates the existing key in place instead of failing.
            conn.execute(
                upsert,
                {"symbol": "VNM", "period": "2026-Q2", "period_type": "quarter",
                 "fiscal_year": 2026, "pe_ratio": 13.0},
            )
            conn.commit()
            rows = conn.execute(
                text(
                    "SELECT pe_ratio FROM financial_ratios "
                    "WHERE symbol='VNM' AND period='2026-Q2' AND period_type='quarter'"
                )
            ).scalars().all()
            assert rows == [13.0]
            assert conn.scalar(text("SELECT count(*) FROM financial_ratios")) == 2

            # Idempotent: re-running the upgrade leaves the constraint and rows intact.
            context = MigrationContext.configure(conn)
            with Operations.context(context), context.begin_transaction():
                migration.upgrade()
            conn.commit()
            assert conn.scalar(text("SELECT count(*) FROM financial_ratios")) == 2

            context = MigrationContext.configure(conn)
            with Operations.context(context), context.begin_transaction():
                migration.downgrade()
            conn.commit()
            assert conn.scalar(
                text(
                    "SELECT count(*) FROM pg_constraint "
                    "WHERE conname = 'uq_financial_ratio_symbol_period' "
                    "AND conrelid = to_regclass('financial_ratios')"
                )
            ) == 0
    finally:
        with engine.begin() as cleanup:
            cleanup.execute(text(f"DROP SCHEMA {schema} CASCADE"))
        engine.dispose()
