// AUTO-GENERATED by scripts/generate-changelog.mjs from CHANGELOG.md.
// Do not edit by hand. Run `pnpm --filter frontend run sync:changelog` to refresh.

const CHANGELOG_MARKDOWN = `# Changelog

All notable changes to VNIBB are documented here. The format is loosely based on
[Keep a Changelog](https://keepachangelog.com/en/1.1.0/) and this project follows
semantic versioning at the user-facing dashboard level.

Sections used: \`Added\`, \`Changed\`, \`Fixed\`, \`Internal\`. "Internal" covers
infra, observability, and developer-facing work that is invisible to users.

Every release passes the standard gate: \`pnpm run ci:gate\` (frontend lint,
build, Jest) plus backend \`ruff\` and \`pytest\`. Individual verification logs
live in \`docs/\`.

## [Unreleased]

### Fixed
- Quant endpoints no longer serve empty price frames: the six historical
  loaders (\`_load_historical_from_*\`, \`_load_corporate_actions_for_adjustment\`,
  \`_apply_corporate_action_adjustments\`) are now re-exported from
  \`vnibb.api.v1.equity\` instead of being shadowed by no-op stubs in \`quant.py\`.
- Postgres connection hardening: \`statement_timeout\`, \`lock_timeout\`, and
  \`idle_in_transaction_session_timeout\` are now applied to every new DBAPI
  connection on both async and sync engines. Defaults are 30s / 5s / 60s and
  can be tuned via \`DB_STATEMENT_TIMEOUT_MS\`, \`DB_LOCK_TIMEOUT_MS\`,
  \`DB_IDLE_IN_TX_TIMEOUT_MS\`.
- \`sync_database_url\` no longer corrupts passwords containing \`+asyncpg\` —
  it now uses a regex anchored to the URL scheme prefix.
- \`/api/v1/health\` now reports the resolved \`appwrite_writes_active\` and
  \`appwrite_configured\` flags (previously the raw \`appwrite_write_enabled\`
  could not distinguish "disabled" from "credentials missing").
- The detailed health endpoint's Redis probe reuses the shared \`redis_client\`
  instead of opening a new connection per request, which removes a leak under
  high health-check load.
- \`AnalystEstimatesWidget\` no longer renders "Coming Soon" placeholder rows
  for empty payloads; it now shows an honest empty-state explaining the
  Vietnam-market coverage gap.

### Internal
- Added \`apps/api/tests/test_core/test_config.py\` covering the new timeout
  settings and the regex-based \`sync_database_url\` derivation.
- Added \`apps/api/tests/test_api/test_quant_loader_aliases.py\` asserting that
  the quant module's helpers resolve to the canonical equity implementations.
- Added \`apps/web/src/components/widgets/AnalystEstimatesWidget.test.tsx\` and
  \`apps/web/src/components/widgets/TickerProfileWidget.test.tsx\` covering
  empty, loading, error, and data states.
- \`scripts/ci-gate.mjs\` now prints a final CI summary table with per-step
  duration, fails fast on the first error, and handles SIGINT/SIGTERM cleanly.
- \`scripts/oracle/healthcheck.sh\` retries each endpoint up to 3 times before
  reporting failure.
- \`scripts/oracle/smoke_test.sh\` validates JSON body shape (not just status
  codes) on critical endpoints and asserts the \`providers.data_backend\`
  field is present in \`/api/v1/health\`.
- \`scripts/oracle/runtime_verify.sh\` accepts an optional \`MCP_HEALTH_URL\` and
  asserts the MCP sidecar responds 200 alongside the API.

## [v1.5.0] - 2026-07-02

The "data flows again" release. End-of-day prices are unstuck, the quant and
global-markets workspaces gained new widgets, and the palette is now
colorblind-safe.

### Added
- Colorblind-safe palette preference in Settings → General. Gains/losses switch
  to a blue/orange scheme applied app-wide, including TradingView charts.
- GARCH(1,1) conditional-volatility widget, seeded into the default quant
  workspace.
- Polymarket prediction-market widget in the Global Markets dashboard, backed by
  the new \`/prediction-markets\` API.
- Frontend \`/api/health\` proxy that surfaces the active data backend without
  leaking backend internals.

### Fixed
- End-of-day prices were frozen for the whole universe: the premium provider no
  longer exposes the legacy quote class, so history now routes through the
  premium \`Quote\` path with a KBS→VCI fallback. Prices advance daily again.
- Mixed-unit EOD prices are normalized at the frame boundary, and fundamental
  market-cap now uses raw-VND close, so valuations stopped drifting by 1000x.
- Key Metrics widget occasionally rendered an unstable payload on slow backends.
- Dashboard grid no longer re-persists layout on unchanged drag echoes.
- Disabled sidebar menu items now expose their state to assistive tech.

### Internal
- Scheduler hardened against stale-data stalls; added the prediction-markets
  sync path.
- Smoke contracts cover the health and freshness endpoints.

## [v1.4.0] - 2026-05-22

The "stability + paper cuts" release. Templates always work, the Financial
Statement tab is no longer blank for stocks with partial provider data, and
the Seasonality Spiral got a real granularity selector.

### Added
- Spiral seasonality heatmap now supports both daily and weekly granularity in a single widget.
- Inline release notes panel renders the full \`CHANGELOG.md\` so users can
  scroll through historical changes without leaving the dashboard.
- Settings → General now includes a "Release Notes" card with a button to
  re-open the What's New panel on demand.
- In-process parity scripts under \`apps/api/scripts/\` for financial
  statements and technical analysis that bypass FastAPI rate limiting.

### Changed
- Applying a template on a locked default dashboard now silently creates a
  fresh editable workspace seeded with the template instead of routing the
  user through a confirmation modal. The "blacked out" template UX is gone.
- Quick-add and empty-tab starter cards on locked dashboards now follow the
  same "auto-create workspace" pattern.
- Seasonality Heatmap weekly columns no longer show the \`W\` prefix in cards,
  tooltips, or the average row. The number speaks for itself.
- What's New panel auto-dismisses after 5 seconds of inactivity and also
  closes when the user switches browser tabs. Hover or focus pauses the
  countdown.
- Sidebar version label is now driven from \`lib/version.ts\` so the sidebar,
  the panel, and analytics all agree on the current release.

### Fixed
- Financial Statement tab rendering blank for tickers where provider returned
  data only under camelCase or Vietnamese-diacritic field names.
- Period mismatch between frontend (\`FY | Q1..Q4 | TTM\`) and backend
  (\`year | quarter | ttm\`) that quietly dropped requests.
- TradingView wrappers occasionally rendering a blank panel when the
  external script timed out; they now retry once and fall back to a clear
  error card with a TradingView deep-link.
- Technical Snapshot widget hanging on slow backends without a retry
  affordance.

### Internal
- Bumped statement endpoint cache key prefix from \`_v2\` to \`_v3\` to evict
  empty-array entries written before the period normalization fix.
- Added concrete \`data_quality.issues\` strings (\`"Only N bars (need >=30)"\`,
  duplicate dates, stale latest bar) instead of opaque flags.
- Centralized release version in \`apps/web/src/lib/version.ts\`.

## [v1.3.0] - 2026-02-25

Sprint V46 - V72 consolidated. Data completeness and pipeline readiness.

### Added
- New backfill scripts for batch financial resync, screener enrichment, and
  ratio refresh under \`apps/api/scripts/\`.
- Peers, TTM aggregates, growth rates, and sector drill-down endpoints for
  parity with the dashboard's analytical surface.
- Dynamic \`/sectors\` symbol population from database metadata with
  market-cap ranking.

### Changed
- Peer selection now prioritizes same-industry peers, then same-exchange,
  then market-cap proximity with deterministic tie-breaking.
- Market heatmap aggregates real database-derived change percentages instead
  of mock values.
- Dividend payloads carry a normalized \`cash | stock | mixed\` payout type,
  annual DPS rollups, and computed yield.
- Header backend-status component requires repeated failures before
  flipping to the offline state, removing flicker on transient blips.

### Fixed
- Sector top movers crashing on null change values; payload key styles are
  now parsed defensively.
- Light-theme readability across header, sidebar, and copilot surfaces.
- Modal and command palette transparency artifacts ("dark stuck" issue).
- Financial period normalization that preferred ordinal counters over the
  reported fiscal year.

### Internal
- Hardened sector top movers against vnstock and vnai quota failures that
  raise \`SystemExit\`.
- Aligned CORS, health route, and websocket routing.
- Added \`data_pipeline\` and \`comparison_service\` ratio fallback hydration.

## [v1.2.0] - 2026-02-22

Sprint V46 - V52. Modal styling, peers/TTM/growth parity, and the first wave
of light-theme work.

### Added
- Peers, TTM aggregates, and growth-rate endpoints (V49 and V50 routes).
- Comparison path aliases plus no-trailing-slash compatibility.
- Custom dashboard templates stored in localStorage with category filtering
  and recommendation surfacing.

### Changed
- Modal and command palette surfaces moved to opaque theme tokens to fix
  transparency issues.
- Empty-tab quick-add actions and stale-tab cleanup at runtime.

### Fixed
- Hidden-container chart dimension warnings via mount guards.
- Heatmap stale-cache fallback and explicit provider timeout guard.

## [v1.1.0] - 2025-12-15

Pre-sprint groundwork. Internal release used to validate the dashboard
shell, widget registry, and the first ten widgets.

### Added
- Multi-tab workspaces with drag-and-drop layout.
- Widget library and template selector.
- TradingView native widget wrappers for chart, ticker tape, and stock
  heatmap.

### Changed
- Migrated from a single-page "stock screen" prototype to the full
  workspace shell.

## [v1.0.0] - 2025-08-10

Initial public preview. Single-stock screen with key metrics, a price chart,
and a basic financial summary.

---

## Conventions

- Versioning follows the dashboard product, not individual API versions.
- Sprint-level work is consolidated into the closest user-facing release.
- Verification details live in dated files under \`docs/\`.
`;

export default CHANGELOG_MARKDOWN;
