"""initial_schema

Revision ID: 1aaa2a1cf198
Revises: 
Create Date: 2026-01-25 08:42:58.778485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aaa2a1cf198'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('block_trade_threshold', sa.Float(), nullable=False),
    sa.Column('enable_insider_buy_alerts', sa.Boolean(), nullable=False),
    sa.Column('enable_insider_sell_alerts', sa.Boolean(), nullable=False),
    sa.Column('enable_ownership_change_alerts', sa.Boolean(), nullable=False),
    sa.Column('ownership_change_threshold', sa.Float(), nullable=False),
    sa.Column('enable_browser_notifications', sa.Boolean(), nullable=False),
    sa.Column('enable_email_notifications', sa.Boolean(), nullable=False),
    sa.Column('enable_sound_alerts', sa.Boolean(), nullable=False),
    sa.Column('notification_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_settings'))
    )
    with op.batch_alter_table('alert_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_settings_user_id'), ['user_id'], unique=True)

    op.create_table('balance_sheets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('current_assets', sa.Float(), nullable=True),
    sa.Column('cash_and_equivalents', sa.Float(), nullable=True),
    sa.Column('short_term_investments', sa.Float(), nullable=True),
    sa.Column('accounts_receivable', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Float(), nullable=True),
    sa.Column('non_current_assets', sa.Float(), nullable=True),
    sa.Column('fixed_assets', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('current_liabilities', sa.Float(), nullable=True),
    sa.Column('accounts_payable', sa.Float(), nullable=True),
    sa.Column('short_term_debt', sa.Float(), nullable=True),
    sa.Column('non_current_liabilities', sa.Float(), nullable=True),
    sa.Column('long_term_debt', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('retained_earnings', sa.Float(), nullable=True),
    sa.Column('book_value_per_share', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_balance_sheets')),
    sa.UniqueConstraint('symbol', 'period', 'period_type', name='uq_balance_sheet_symbol_period')
    )
    with op.batch_alter_table('balance_sheets', schema=None) as batch_op:
        batch_op.create_index('ix_balance_sheet_symbol_year', ['symbol', 'fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_sheets_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_sheets_symbol'), ['symbol'], unique=False)

    op.create_table('block_trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='tradeside'), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('trade_time', sa.DateTime(), nullable=False),
    sa.Column('counterparty', sa.String(length=100), nullable=True),
    sa.Column('is_foreign', sa.Boolean(), nullable=False),
    sa.Column('is_proprietary', sa.Boolean(), nullable=False),
    sa.Column('avg_volume_20d', sa.BigInteger(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_block_trades'))
    )
    with op.batch_alter_table('block_trades', schema=None) as batch_op:
        batch_op.create_index('ix_block_symbol_time', ['symbol', 'trade_time'], unique=False)
        batch_op.create_index('ix_block_time', ['trade_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_trades_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_trades_trade_time'), ['trade_time'], unique=False)
        batch_op.create_index('ix_block_value', ['value'], unique=False)

    op.create_table('cash_flows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('depreciation', sa.Float(), nullable=True),
    sa.Column('investing_cash_flow', sa.Float(), nullable=True),
    sa.Column('capital_expenditure', sa.Float(), nullable=True),
    sa.Column('financing_cash_flow', sa.Float(), nullable=True),
    sa.Column('dividends_paid', sa.Float(), nullable=True),
    sa.Column('debt_repayment', sa.Float(), nullable=True),
    sa.Column('net_change_in_cash', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_flows')),
    sa.UniqueConstraint('symbol', 'period', 'period_type', name='uq_cash_flow_symbol_period')
    )
    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.create_index('ix_cash_flow_symbol_year', ['symbol', 'fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_flows_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_flows_symbol'), ['symbol'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('english_name', sa.String(length=255), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('subsector', sa.String(length=100), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('outstanding_shares', sa.Float(), nullable=True),
    sa.Column('listed_shares', sa.Float(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_symbol'), ['symbol'], unique=True)

    op.create_table('company_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_events')),
    sa.UniqueConstraint('symbol', 'event_type', 'event_date', name='uq_event_symbol_type_date')
    )
    with op.batch_alter_table('company_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_events_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_event_symbol_date', ['symbol', 'event_date'], unique=False)
        batch_op.create_index('ix_event_type_date', ['event_type', 'event_date'], unique=False)

    op.create_table('company_news',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('rs', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_change', sa.Float(), nullable=True),
    sa.Column('price_change_ratio', sa.Float(), nullable=True),
    sa.Column('news_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_news')),
    sa.UniqueConstraint('symbol', 'title', 'published_date', name='uq_news_symbol_title_date')
    )
    with op.batch_alter_table('company_news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_news_published_date'), ['published_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_news_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_news_source', ['source'], unique=False)
        batch_op.create_index('ix_news_symbol_published', ['symbol', 'published_date'], unique=False)

    op.create_table('dividends',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('exercise_date', sa.Date(), nullable=True),
    sa.Column('cash_year', sa.Integer(), nullable=True),
    sa.Column('dividend_rate', sa.Float(), nullable=True),
    sa.Column('dividend_value', sa.Float(), nullable=True),
    sa.Column('issue_method', sa.String(length=50), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dividends')),
    sa.UniqueConstraint('symbol', 'exercise_date', 'cash_year', name='uq_dividend_symbol_date_year')
    )
    with op.batch_alter_table('dividends', schema=None) as batch_op:
        batch_op.create_index('ix_dividend_symbol_date', ['symbol', 'exercise_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividends_exercise_date'), ['exercise_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividends_symbol'), ['symbol'], unique=False)

    op.create_table('financial_ratios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('ps_ratio', sa.Float(), nullable=True),
    sa.Column('peg_ratio', sa.Float(), nullable=True),
    sa.Column('ev_ebitda', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('roic', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('quick_ratio', sa.Float(), nullable=True),
    sa.Column('cash_ratio', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('debt_to_assets', sa.Float(), nullable=True),
    sa.Column('interest_coverage', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('bvps', sa.Float(), nullable=True),
    sa.Column('dps', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('earnings_growth', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_ratios')),
    sa.UniqueConstraint('symbol', 'period', 'period_type', name='uq_financial_ratio_symbol_period')
    )
    with op.batch_alter_table('financial_ratios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_ratios_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_ratios_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_ratio_symbol_year', ['symbol', 'fiscal_year'], unique=False)

    op.create_table('foreign_trading',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('buy_volume', sa.BigInteger(), nullable=True),
    sa.Column('buy_value', sa.Float(), nullable=True),
    sa.Column('sell_volume', sa.BigInteger(), nullable=True),
    sa.Column('sell_value', sa.Float(), nullable=True),
    sa.Column('net_volume', sa.BigInteger(), nullable=True),
    sa.Column('net_value', sa.Float(), nullable=True),
    sa.Column('room_available', sa.Float(), nullable=True),
    sa.Column('room_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foreign_trading')),
    sa.UniqueConstraint('symbol', 'trade_date', name='uq_foreign_trading_symbol_date')
    )
    with op.batch_alter_table('foreign_trading', schema=None) as batch_op:
        batch_op.create_index('ix_foreign_symbol_date', ['symbol', 'trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_foreign_trading_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_foreign_trading_trade_date'), ['trade_date'], unique=False)

    op.create_table('income_statements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('cost_of_revenue', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('operating_expenses', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.Float(), nullable=True),
    sa.Column('interest_expense', sa.Float(), nullable=True),
    sa.Column('other_income', sa.Float(), nullable=True),
    sa.Column('income_before_tax', sa.Float(), nullable=True),
    sa.Column('income_tax', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('eps_diluted', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_income_statements')),
    sa.UniqueConstraint('symbol', 'period', 'period_type', name='uq_income_stmt_symbol_period')
    )
    with op.batch_alter_table('income_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_statements_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_statements_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_income_stmt_perf', ['symbol', 'net_income'], unique=False)
        batch_op.create_index('ix_income_stmt_symbol_year', ['symbol', 'fiscal_year'], unique=False)

    op.create_table('insider_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.Enum('INSIDER_BUY', 'INSIDER_SELL', 'BLOCK_TRADE', 'OWNERSHIP_CHANGE', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='alertseverity'), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('insider_deal_id', sa.BigInteger(), nullable=True),
    sa.Column('block_trade_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insider_alerts'))
    )
    with op.batch_alter_table('insider_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alert_symbol_time', ['symbol', 'timestamp'], unique=False)
        batch_op.create_index('ix_alert_type_time', ['alert_type', 'timestamp'], unique=False)
        batch_op.create_index('ix_alert_user_read', ['user_id', 'read'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_alerts_read'), ['read'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_alerts_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_alerts_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('insider_deals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('announce_date', sa.Date(), nullable=False),
    sa.Column('deal_method', sa.String(length=50), nullable=True),
    sa.Column('deal_action', sa.String(length=10), nullable=True),
    sa.Column('deal_quantity', sa.Float(), nullable=True),
    sa.Column('deal_price', sa.Float(), nullable=True),
    sa.Column('deal_value', sa.Float(), nullable=True),
    sa.Column('deal_ratio', sa.Float(), nullable=True),
    sa.Column('insider_name', sa.String(length=255), nullable=True),
    sa.Column('insider_position', sa.String(length=100), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insider_deals'))
    )
    with op.batch_alter_table('insider_deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insider_deals_announce_date'), ['announce_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_deals_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_insider_symbol_date', ['symbol', 'announce_date'], unique=False)

    op.create_table('intraday_trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('trade_time', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=10), nullable=True),
    sa.Column('accumulated_vol', sa.BigInteger(), nullable=True),
    sa.Column('accumulated_val', sa.Float(), nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intraday_trades'))
    )
    with op.batch_alter_table('intraday_trades', schema=None) as batch_op:
        batch_op.create_index('ix_intraday_symbol_time', ['symbol', 'trade_time'], unique=False)
        batch_op.create_index('ix_intraday_time', ['trade_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_intraday_trades_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_intraday_trades_trade_time'), ['trade_time'], unique=False)

    op.create_table('market_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('related_symbols', sa.String(length=200), nullable=True),
    sa.Column('sectors', sa.String(length=200), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=False),
    sa.Column('bookmark_count', sa.Integer(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_news')),
    sa.UniqueConstraint('url', name=op.f('uq_market_news_url'))
    )
    with op.batch_alter_table('market_news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_news_is_processed'), ['is_processed'], unique=False)
        batch_op.create_index('ix_market_news_published', ['published_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_news_published_date'), ['published_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_news_related_symbols'), ['related_symbols'], unique=False)
        batch_op.create_index('ix_market_news_sentiment', ['sentiment', 'published_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_news_source'), ['source'], unique=False)
        batch_op.create_index('ix_market_news_source_date', ['source', 'published_date'], unique=False)

    op.create_table('market_sectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sector_code', sa.String(length=20), nullable=False),
    sa.Column('sector_name', sa.String(length=100), nullable=False),
    sa.Column('sector_name_en', sa.String(length=100), nullable=True),
    sa.Column('parent_code', sa.String(length=20), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('icb_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_sectors'))
    )
    with op.batch_alter_table('market_sectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_sectors_sector_code'), ['sector_code'], unique=True)

    op.create_table('orderbook_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('price_depth', sa.JSON(), nullable=True),
    sa.Column('bid1_price', sa.Float(), nullable=True),
    sa.Column('bid1_volume', sa.BigInteger(), nullable=True),
    sa.Column('bid2_price', sa.Float(), nullable=True),
    sa.Column('bid2_volume', sa.BigInteger(), nullable=True),
    sa.Column('bid3_price', sa.Float(), nullable=True),
    sa.Column('bid3_volume', sa.BigInteger(), nullable=True),
    sa.Column('ask1_price', sa.Float(), nullable=True),
    sa.Column('ask1_volume', sa.BigInteger(), nullable=True),
    sa.Column('ask2_price', sa.Float(), nullable=True),
    sa.Column('ask2_volume', sa.BigInteger(), nullable=True),
    sa.Column('ask3_price', sa.Float(), nullable=True),
    sa.Column('ask3_volume', sa.BigInteger(), nullable=True),
    sa.Column('total_bid_volume', sa.BigInteger(), nullable=True),
    sa.Column('total_ask_volume', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orderbook_snapshots'))
    )
    with op.batch_alter_table('orderbook_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orderbook_snapshots_snapshot_time'), ['snapshot_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_orderbook_snapshots_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_orderbook_symbol_time', ['symbol', 'snapshot_time'], unique=False)

    op.create_table('screener_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('ps', sa.Float(), nullable=True),
    sa.Column('ev_ebitda', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('roic', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('earnings_growth', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('quick_ratio', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('bvps', sa.Float(), nullable=True),
    sa.Column('foreign_ownership', sa.Float(), nullable=True),
    sa.Column('rs_rating', sa.Float(), nullable=True),
    sa.Column('rs_rank', sa.Integer(), nullable=True),
    sa.Column('extended_metrics', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screener_snapshots')),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_screener_snapshot_symbol_date')
    )
    with op.batch_alter_table('screener_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_screener_date_industry', ['snapshot_date', 'industry'], unique=False)
        batch_op.create_index('ix_screener_date_market_cap', ['snapshot_date', 'market_cap'], unique=False)
        batch_op.create_index('ix_screener_date_rs', ['snapshot_date', 'rs_rating'], unique=False)
        batch_op.create_index('ix_screener_market_cap', ['market_cap'], unique=False)
        batch_op.create_index(batch_op.f('ix_screener_snapshots_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_screener_snapshots_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_screener_snapshots_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_screener_symbol_date', ['symbol', 'snapshot_date'], unique=False)

    op.create_table('sector_performance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sector_code', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('avg_change_pct', sa.Float(), nullable=True),
    sa.Column('total_volume', sa.BigInteger(), nullable=True),
    sa.Column('avg_volume', sa.BigInteger(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('total_market_cap', sa.Float(), nullable=True),
    sa.Column('top_gainer_symbol', sa.String(length=10), nullable=True),
    sa.Column('top_gainer_change', sa.Float(), nullable=True),
    sa.Column('top_loser_symbol', sa.String(length=10), nullable=True),
    sa.Column('top_loser_change', sa.Float(), nullable=True),
    sa.Column('advance_count', sa.Integer(), nullable=True),
    sa.Column('decline_count', sa.Integer(), nullable=True),
    sa.Column('unchanged_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sector_performance')),
    sa.UniqueConstraint('sector_code', 'trade_date', name='uq_sector_perf_code_date')
    )
    with op.batch_alter_table('sector_performance', schema=None) as batch_op:
        batch_op.create_index('ix_sector_perf_date', ['trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sector_performance_sector_code'), ['sector_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sector_performance_trade_date'), ['trade_date'], unique=False)

    op.create_table('stock_indices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('index_code', sa.String(length=20), nullable=False),
    sa.Column('time', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_indices')),
    sa.UniqueConstraint('index_code', 'time', name='uq_stock_index_code_time')
    )
    with op.batch_alter_table('stock_indices', schema=None) as batch_op:
        batch_op.create_index('ix_stock_index_code_time', ['index_code', 'time'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_indices_index_code'), ['index_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_indices_time'), ['time'], unique=False)

    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('delisting_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocks')),
    sa.UniqueConstraint('isin', name=op.f('uq_stocks_isin'))
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocks_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocks_symbol'), ['symbol'], unique=True)

    op.create_table('subsidiaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('subsidiary_name', sa.String(length=255), nullable=False),
    sa.Column('subsidiary_symbol', sa.String(length=10), nullable=True),
    sa.Column('ownership_pct', sa.Float(), nullable=True),
    sa.Column('charter_capital', sa.Float(), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subsidiaries'))
    )
    with op.batch_alter_table('subsidiaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subsidiaries_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_subsidiary_symbol', ['symbol'], unique=False)

    op.create_table('sync_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_status'))
    )
    with op.batch_alter_table('sync_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_status_sync_type'), ['sync_type'], unique=False)

    op.create_table('technical_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('calc_date', sa.Date(), nullable=False),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('ema_12', sa.Float(), nullable=True),
    sa.Column('ema_26', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('stoch_k', sa.Float(), nullable=True),
    sa.Column('stoch_d', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_hist', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_middle', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('obv', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_indicators')),
    sa.UniqueConstraint('symbol', 'calc_date', name='uq_technical_indicator_symbol_date')
    )
    with op.batch_alter_table('technical_indicators', schema=None) as batch_op:
        batch_op.create_index('ix_ta_symbol_date', ['symbol', 'calc_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_technical_indicators_symbol'), ['symbol'], unique=False)

    op.create_table('user_dashboards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('layout_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_dashboards'))
    )
    with op.batch_alter_table('user_dashboards', schema=None) as batch_op:
        batch_op.create_index('ix_dashboard_user_default', ['user_id', 'is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_dashboards_user_id'), ['user_id'], unique=False)

    op.create_table('dashboard_widgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.String(length=50), nullable=False),
    sa.Column('widget_type', sa.String(length=50), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('widget_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['user_dashboards.id'], name=op.f('fk_dashboard_widgets_dashboard_id_user_dashboards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_widgets'))
    )
    with op.batch_alter_table('dashboard_widgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_widgets_dashboard_id'), ['dashboard_id'], unique=False)

    op.create_table('officers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('position_type', sa.String(length=50), nullable=True),
    sa.Column('shares_held', sa.Float(), nullable=True),
    sa.Column('ownership_pct', sa.Float(), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_officers_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_officers'))
    )
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.create_index('ix_officer_symbol', ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_officers_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_officers_symbol'), ['symbol'], unique=False)

    op.create_table('shareholders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shareholder_type', sa.String(length=50), nullable=True),
    sa.Column('shares_held', sa.Float(), nullable=True),
    sa.Column('ownership_pct', sa.Float(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_shareholders_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shareholders'))
    )
    with op.batch_alter_table('shareholders', schema=None) as batch_op:
        batch_op.create_index('ix_shareholder_symbol_type', ['symbol', 'shareholder_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholders_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shareholders_symbol'), ['symbol'], unique=False)

    op.create_table('stock_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('time', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('interval', sa.String(length=5), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_stock_prices_stock_id_stocks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_prices')),
    sa.UniqueConstraint('symbol', 'time', 'interval', name='uq_stock_price_symbol_time_interval')
    )
    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.create_index('ix_stock_price_date_only', ['time'], unique=False)
        batch_op.create_index('ix_stock_price_perf', ['symbol', 'close'], unique=False)
        batch_op.create_index('ix_stock_price_symbol_time', ['symbol', 'time'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_prices_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_prices_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_prices_time'), ['time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_prices_time'))
        batch_op.drop_index(batch_op.f('ix_stock_prices_symbol'))
        batch_op.drop_index(batch_op.f('ix_stock_prices_stock_id'))
        batch_op.drop_index('ix_stock_price_symbol_time')
        batch_op.drop_index('ix_stock_price_perf')
        batch_op.drop_index('ix_stock_price_date_only')

    op.drop_table('stock_prices')
    with op.batch_alter_table('shareholders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shareholders_symbol'))
        batch_op.drop_index(batch_op.f('ix_shareholders_company_id'))
        batch_op.drop_index('ix_shareholder_symbol_type')

    op.drop_table('shareholders')
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_officers_symbol'))
        batch_op.drop_index(batch_op.f('ix_officers_company_id'))
        batch_op.drop_index('ix_officer_symbol')

    op.drop_table('officers')
    with op.batch_alter_table('dashboard_widgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_widgets_dashboard_id'))

    op.drop_table('dashboard_widgets')
    with op.batch_alter_table('user_dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_dashboards_user_id'))
        batch_op.drop_index('ix_dashboard_user_default')

    op.drop_table('user_dashboards')
    with op.batch_alter_table('technical_indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technical_indicators_symbol'))
        batch_op.drop_index('ix_ta_symbol_date')

    op.drop_table('technical_indicators')
    with op.batch_alter_table('sync_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_status_sync_type'))

    op.drop_table('sync_status')
    with op.batch_alter_table('subsidiaries', schema=None) as batch_op:
        batch_op.drop_index('ix_subsidiary_symbol')
        batch_op.drop_index(batch_op.f('ix_subsidiaries_symbol'))

    op.drop_table('subsidiaries')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_symbol'))
        batch_op.drop_index(batch_op.f('ix_stocks_industry'))
        batch_op.drop_index(batch_op.f('ix_stocks_exchange'))

    op.drop_table('stocks')
    with op.batch_alter_table('stock_indices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_indices_time'))
        batch_op.drop_index(batch_op.f('ix_stock_indices_index_code'))
        batch_op.drop_index('ix_stock_index_code_time')

    op.drop_table('stock_indices')
    with op.batch_alter_table('sector_performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sector_performance_trade_date'))
        batch_op.drop_index(batch_op.f('ix_sector_performance_sector_code'))
        batch_op.drop_index('ix_sector_perf_date')

    op.drop_table('sector_performance')
    with op.batch_alter_table('screener_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_screener_symbol_date')
        batch_op.drop_index(batch_op.f('ix_screener_snapshots_symbol'))
        batch_op.drop_index(batch_op.f('ix_screener_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_screener_snapshots_industry'))
        batch_op.drop_index('ix_screener_market_cap')
        batch_op.drop_index('ix_screener_date_rs')
        batch_op.drop_index('ix_screener_date_market_cap')
        batch_op.drop_index('ix_screener_date_industry')

    op.drop_table('screener_snapshots')
    with op.batch_alter_table('orderbook_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_orderbook_symbol_time')
        batch_op.drop_index(batch_op.f('ix_orderbook_snapshots_symbol'))
        batch_op.drop_index(batch_op.f('ix_orderbook_snapshots_snapshot_time'))

    op.drop_table('orderbook_snapshots')
    with op.batch_alter_table('market_sectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_sectors_sector_code'))

    op.drop_table('market_sectors')
    with op.batch_alter_table('market_news', schema=None) as batch_op:
        batch_op.drop_index('ix_market_news_source_date')
        batch_op.drop_index(batch_op.f('ix_market_news_source'))
        batch_op.drop_index('ix_market_news_sentiment')
        batch_op.drop_index(batch_op.f('ix_market_news_related_symbols'))
        batch_op.drop_index(batch_op.f('ix_market_news_published_date'))
        batch_op.drop_index('ix_market_news_published')
        batch_op.drop_index(batch_op.f('ix_market_news_is_processed'))

    op.drop_table('market_news')
    with op.batch_alter_table('intraday_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intraday_trades_trade_time'))
        batch_op.drop_index(batch_op.f('ix_intraday_trades_symbol'))
        batch_op.drop_index('ix_intraday_time')
        batch_op.drop_index('ix_intraday_symbol_time')

    op.drop_table('intraday_trades')
    with op.batch_alter_table('insider_deals', schema=None) as batch_op:
        batch_op.drop_index('ix_insider_symbol_date')
        batch_op.drop_index(batch_op.f('ix_insider_deals_symbol'))
        batch_op.drop_index(batch_op.f('ix_insider_deals_announce_date'))

    op.drop_table('insider_deals')
    with op.batch_alter_table('insider_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insider_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_insider_alerts_timestamp'))
        batch_op.drop_index(batch_op.f('ix_insider_alerts_symbol'))
        batch_op.drop_index(batch_op.f('ix_insider_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_insider_alerts_read'))
        batch_op.drop_index(batch_op.f('ix_insider_alerts_alert_type'))
        batch_op.drop_index('ix_alert_user_read')
        batch_op.drop_index('ix_alert_type_time')
        batch_op.drop_index('ix_alert_symbol_time')

    op.drop_table('insider_alerts')
    with op.batch_alter_table('income_statements', schema=None) as batch_op:
        batch_op.drop_index('ix_income_stmt_symbol_year')
        batch_op.drop_index('ix_income_stmt_perf')
        batch_op.drop_index(batch_op.f('ix_income_statements_symbol'))
        batch_op.drop_index(batch_op.f('ix_income_statements_fiscal_year'))

    op.drop_table('income_statements')
    with op.batch_alter_table('foreign_trading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foreign_trading_trade_date'))
        batch_op.drop_index(batch_op.f('ix_foreign_trading_symbol'))
        batch_op.drop_index('ix_foreign_symbol_date')

    op.drop_table('foreign_trading')
    with op.batch_alter_table('financial_ratios', schema=None) as batch_op:
        batch_op.drop_index('ix_ratio_symbol_year')
        batch_op.drop_index(batch_op.f('ix_financial_ratios_symbol'))
        batch_op.drop_index(batch_op.f('ix_financial_ratios_fiscal_year'))

    op.drop_table('financial_ratios')
    with op.batch_alter_table('dividends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dividends_symbol'))
        batch_op.drop_index(batch_op.f('ix_dividends_exercise_date'))
        batch_op.drop_index('ix_dividend_symbol_date')

    op.drop_table('dividends')
    with op.batch_alter_table('company_news', schema=None) as batch_op:
        batch_op.drop_index('ix_news_symbol_published')
        batch_op.drop_index('ix_news_source')
        batch_op.drop_index(batch_op.f('ix_company_news_symbol'))
        batch_op.drop_index(batch_op.f('ix_company_news_published_date'))

    op.drop_table('company_news')
    with op.batch_alter_table('company_events', schema=None) as batch_op:
        batch_op.drop_index('ix_event_type_date')
        batch_op.drop_index('ix_event_symbol_date')
        batch_op.drop_index(batch_op.f('ix_company_events_symbol'))
        batch_op.drop_index(batch_op.f('ix_company_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_company_events_event_date'))

    op.drop_table('company_events')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_symbol'))

    op.drop_table('companies')
    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_flows_symbol'))
        batch_op.drop_index(batch_op.f('ix_cash_flows_fiscal_year'))
        batch_op.drop_index('ix_cash_flow_symbol_year')

    op.drop_table('cash_flows')
    with op.batch_alter_table('block_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_block_value')
        batch_op.drop_index(batch_op.f('ix_block_trades_trade_time'))
        batch_op.drop_index(batch_op.f('ix_block_trades_symbol'))
        batch_op.drop_index('ix_block_time')
        batch_op.drop_index('ix_block_symbol_time')

    op.drop_table('block_trades')
    with op.batch_alter_table('balance_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_sheets_symbol'))
        batch_op.drop_index(batch_op.f('ix_balance_sheets_fiscal_year'))
        batch_op.drop_index('ix_balance_sheet_symbol_year')

    op.drop_table('balance_sheets')
    with op.batch_alter_table('alert_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_settings_user_id'))

    op.drop_table('alert_settings')
    # ### end Alembic commands ###
