"""add_sync_status_additional_data

Revision ID: 9abd9cdc70b6
Revises: 5a74881719e
Create Date: 2026-01-17 16:24:12.606466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9abd9cdc70b6'
down_revision: Union[str, None] = '5a74881719e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balance_sheet_lookup'), table_name='balance_sheets')
    op.drop_index(op.f('ix_cash_flow_lookup'), table_name='cash_flows')
    op.drop_index(op.f('ix_company_news_published_at'), table_name='company_news')
    op.drop_index(op.f('ix_income_stmt_lookup'), table_name='income_statements')
    op.alter_column('screener_snapshots', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_screener_date_market_cap_pe'), table_name='screener_snapshots')
    op.drop_index(op.f('ix_stock_prices_symbol_interval_time'), table_name='stock_prices')
    op.add_column('sync_status', sa.Column('additional_data', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_sync_status_started_at'), table_name='sync_status')
    op.drop_column('sync_status', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_status', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_sync_status_started_at'), 'sync_status', ['started_at'], unique=False)
    op.drop_column('sync_status', 'additional_data')
    op.create_index(op.f('ix_stock_prices_symbol_interval_time'), 'stock_prices', ['symbol', 'interval', 'time'], unique=False)
    op.create_index(op.f('ix_screener_date_market_cap_pe'), 'screener_snapshots', ['snapshot_date', 'market_cap', 'pe'], unique=False)
    op.alter_column('screener_snapshots', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_income_stmt_lookup'), 'income_statements', ['symbol', 'period_type', 'fiscal_year'], unique=False)
    op.create_index(op.f('ix_company_news_published_at'), 'company_news', ['published_date'], unique=False)
    op.create_index(op.f('ix_cash_flow_lookup'), 'cash_flows', ['symbol', 'period_type', 'fiscal_year'], unique=False)
    op.create_index(op.f('ix_balance_sheet_lookup'), 'balance_sheets', ['symbol', 'period_type', 'fiscal_year'], unique=False)
    # ### end Alembic commands ###
