"""Add insider trading and block trade alerts models

Revision ID: a0fc7ce48b87
Revises: 49a74881719d
Create Date: 2026-01-14 02:01:24.232185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0fc7ce48b87'
down_revision: Union[str, None] = '49a74881719d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('block_trade_threshold', sa.Float(), nullable=False),
    sa.Column('enable_insider_buy_alerts', sa.Boolean(), nullable=False),
    sa.Column('enable_insider_sell_alerts', sa.Boolean(), nullable=False),
    sa.Column('enable_ownership_change_alerts', sa.Boolean(), nullable=False),
    sa.Column('ownership_change_threshold', sa.Float(), nullable=False),
    sa.Column('enable_browser_notifications', sa.Boolean(), nullable=False),
    sa.Column('enable_email_notifications', sa.Boolean(), nullable=False),
    sa.Column('enable_sound_alerts', sa.Boolean(), nullable=False),
    sa.Column('notification_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_settings'))
    )
    op.create_index(op.f('ix_alert_settings_user_id'), 'alert_settings', ['user_id'], unique=True)
    op.create_table('block_trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='tradeside'), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('trade_time', sa.DateTime(), nullable=False),
    sa.Column('counterparty', sa.String(length=100), nullable=True),
    sa.Column('is_foreign', sa.Boolean(), nullable=False),
    sa.Column('is_proprietary', sa.Boolean(), nullable=False),
    sa.Column('avg_volume_20d', sa.BigInteger(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_block_trades'))
    )
    op.create_index('ix_block_symbol_time', 'block_trades', ['symbol', 'trade_time'], unique=False)
    op.create_index('ix_block_time', 'block_trades', ['trade_time'], unique=False)
    op.create_index(op.f('ix_block_trades_symbol'), 'block_trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_block_trades_trade_time'), 'block_trades', ['trade_time'], unique=False)
    op.create_index('ix_block_value', 'block_trades', ['value'], unique=False)
    op.create_table('insider_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.Enum('INSIDER_BUY', 'INSIDER_SELL', 'BLOCK_TRADE', 'OWNERSHIP_CHANGE', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='alertseverity'), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('insider_deal_id', sa.BigInteger(), nullable=True),
    sa.Column('block_trade_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insider_alerts'))
    )
    op.create_index('ix_alert_symbol_time', 'insider_alerts', ['symbol', 'timestamp'], unique=False)
    op.create_index('ix_alert_type_time', 'insider_alerts', ['alert_type', 'timestamp'], unique=False)
    op.create_index('ix_alert_user_read', 'insider_alerts', ['user_id', 'read'], unique=False)
    op.create_index(op.f('ix_insider_alerts_alert_type'), 'insider_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_insider_alerts_read'), 'insider_alerts', ['read'], unique=False)
    op.create_index(op.f('ix_insider_alerts_severity'), 'insider_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_insider_alerts_symbol'), 'insider_alerts', ['symbol'], unique=False)
    op.create_index(op.f('ix_insider_alerts_timestamp'), 'insider_alerts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_insider_alerts_user_id'), 'insider_alerts', ['user_id'], unique=False)
    op.drop_index(op.f('ix_market_news_sentiment'), table_name='market_news')
    op.create_index('ix_market_news_sentiment', 'market_news', ['sentiment', 'published_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_news_sentiment', table_name='market_news')
    op.create_index(op.f('ix_market_news_sentiment'), 'market_news', ['sentiment'], unique=False)
    op.drop_index(op.f('ix_insider_alerts_user_id'), table_name='insider_alerts')
    op.drop_index(op.f('ix_insider_alerts_timestamp'), table_name='insider_alerts')
    op.drop_index(op.f('ix_insider_alerts_symbol'), table_name='insider_alerts')
    op.drop_index(op.f('ix_insider_alerts_severity'), table_name='insider_alerts')
    op.drop_index(op.f('ix_insider_alerts_read'), table_name='insider_alerts')
    op.drop_index(op.f('ix_insider_alerts_alert_type'), table_name='insider_alerts')
    op.drop_index('ix_alert_user_read', table_name='insider_alerts')
    op.drop_index('ix_alert_type_time', table_name='insider_alerts')
    op.drop_index('ix_alert_symbol_time', table_name='insider_alerts')
    op.drop_table('insider_alerts')
    op.drop_index('ix_block_value', table_name='block_trades')
    op.drop_index(op.f('ix_block_trades_trade_time'), table_name='block_trades')
    op.drop_index(op.f('ix_block_trades_symbol'), table_name='block_trades')
    op.drop_index('ix_block_time', table_name='block_trades')
    op.drop_index('ix_block_symbol_time', table_name='block_trades')
    op.drop_table('block_trades')
    op.drop_index(op.f('ix_alert_settings_user_id'), table_name='alert_settings')
    op.drop_table('alert_settings')
    # ### end Alembic commands ###
