"""Add sentiment analysis fields to market_news

Revision ID: 49a74881719d
Revises: 0001_initial
Create Date: 2026-01-14 01:44:26.122187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49a74881719d'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_events')),
    sa.UniqueConstraint('symbol', 'event_type', 'event_date', name='uq_event_symbol_type_date')
    )
    op.create_index(op.f('ix_company_events_event_date'), 'company_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_company_events_event_type'), 'company_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_company_events_symbol'), 'company_events', ['symbol'], unique=False)
    op.create_index('ix_event_symbol_date', 'company_events', ['symbol', 'event_date'], unique=False)
    op.create_index('ix_event_type_date', 'company_events', ['event_type', 'event_date'], unique=False)
    op.create_table('company_news',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('rs', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_change', sa.Float(), nullable=True),
    sa.Column('price_change_ratio', sa.Float(), nullable=True),
    sa.Column('news_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_news')),
    sa.UniqueConstraint('symbol', 'title', 'published_date', name='uq_news_symbol_title_date')
    )
    op.create_index(op.f('ix_company_news_published_date'), 'company_news', ['published_date'], unique=False)
    op.create_index(op.f('ix_company_news_symbol'), 'company_news', ['symbol'], unique=False)
    op.create_index('ix_news_symbol_published', 'company_news', ['symbol', 'published_date'], unique=False)
    op.create_table('dividends',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('exercise_date', sa.Date(), nullable=True),
    sa.Column('cash_year', sa.Integer(), nullable=True),
    sa.Column('dividend_rate', sa.Float(), nullable=True),
    sa.Column('dividend_value', sa.Float(), nullable=True),
    sa.Column('issue_method', sa.String(length=50), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dividends')),
    sa.UniqueConstraint('symbol', 'exercise_date', 'cash_year', name='uq_dividend_symbol_date_year')
    )
    op.create_index('ix_dividend_symbol_date', 'dividends', ['symbol', 'exercise_date'], unique=False)
    op.create_index(op.f('ix_dividends_exercise_date'), 'dividends', ['exercise_date'], unique=False)
    op.create_index(op.f('ix_dividends_symbol'), 'dividends', ['symbol'], unique=False)
    op.create_table('financial_ratios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('ps_ratio', sa.Float(), nullable=True),
    sa.Column('peg_ratio', sa.Float(), nullable=True),
    sa.Column('ev_ebitda', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('roic', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('quick_ratio', sa.Float(), nullable=True),
    sa.Column('cash_ratio', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('debt_to_assets', sa.Float(), nullable=True),
    sa.Column('interest_coverage', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('bvps', sa.Float(), nullable=True),
    sa.Column('dps', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('earnings_growth', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_ratios')),
    sa.UniqueConstraint('symbol', 'period', 'period_type', name='uq_financial_ratio_symbol_period')
    )
    op.create_index(op.f('ix_financial_ratios_fiscal_year'), 'financial_ratios', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_financial_ratios_symbol'), 'financial_ratios', ['symbol'], unique=False)
    op.create_index('ix_ratio_symbol_year', 'financial_ratios', ['symbol', 'fiscal_year'], unique=False)
    op.create_table('foreign_trading',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('buy_volume', sa.BigInteger(), nullable=True),
    sa.Column('buy_value', sa.Float(), nullable=True),
    sa.Column('sell_volume', sa.BigInteger(), nullable=True),
    sa.Column('sell_value', sa.Float(), nullable=True),
    sa.Column('net_volume', sa.BigInteger(), nullable=True),
    sa.Column('net_value', sa.Float(), nullable=True),
    sa.Column('room_available', sa.Float(), nullable=True),
    sa.Column('room_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foreign_trading')),
    sa.UniqueConstraint('symbol', 'trade_date', name='uq_foreign_trading_symbol_date')
    )
    op.create_index('ix_foreign_symbol_date', 'foreign_trading', ['symbol', 'trade_date'], unique=False)
    op.create_index(op.f('ix_foreign_trading_symbol'), 'foreign_trading', ['symbol'], unique=False)
    op.create_index(op.f('ix_foreign_trading_trade_date'), 'foreign_trading', ['trade_date'], unique=False)
    op.create_table('insider_deals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('announce_date', sa.Date(), nullable=False),
    sa.Column('deal_method', sa.String(length=50), nullable=True),
    sa.Column('deal_action', sa.String(length=10), nullable=True),
    sa.Column('deal_quantity', sa.Float(), nullable=True),
    sa.Column('deal_price', sa.Float(), nullable=True),
    sa.Column('deal_value', sa.Float(), nullable=True),
    sa.Column('deal_ratio', sa.Float(), nullable=True),
    sa.Column('insider_name', sa.String(length=255), nullable=True),
    sa.Column('insider_position', sa.String(length=100), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insider_deals'))
    )
    op.create_index(op.f('ix_insider_deals_announce_date'), 'insider_deals', ['announce_date'], unique=False)
    op.create_index(op.f('ix_insider_deals_symbol'), 'insider_deals', ['symbol'], unique=False)
    op.create_index('ix_insider_symbol_date', 'insider_deals', ['symbol', 'announce_date'], unique=False)
    op.create_table('intraday_trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('trade_time', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=10), nullable=True),
    sa.Column('accumulated_vol', sa.BigInteger(), nullable=True),
    sa.Column('accumulated_val', sa.Float(), nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intraday_trades'))
    )
    op.create_index('ix_intraday_symbol_time', 'intraday_trades', ['symbol', 'trade_time'], unique=False)
    op.create_index('ix_intraday_time', 'intraday_trades', ['trade_time'], unique=False)
    op.create_index(op.f('ix_intraday_trades_symbol'), 'intraday_trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_intraday_trades_trade_time'), 'intraday_trades', ['trade_time'], unique=False)
    op.create_table('market_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('related_symbols', sa.String(length=200), nullable=True),
    sa.Column('sectors', sa.String(length=200), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=False),
    sa.Column('bookmark_count', sa.Integer(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_news')),
    sa.UniqueConstraint('url', name=op.f('uq_market_news_url'))
    )
    op.create_index(op.f('ix_market_news_is_processed'), 'market_news', ['is_processed'], unique=False)
    op.create_index('ix_market_news_published', 'market_news', ['published_date'], unique=False)
    op.create_index(op.f('ix_market_news_published_date'), 'market_news', ['published_date'], unique=False)
    op.create_index(op.f('ix_market_news_related_symbols'), 'market_news', ['related_symbols'], unique=False)
    op.create_index(op.f('ix_market_news_sentiment'), 'market_news', ['sentiment'], unique=False)
    op.create_index(op.f('ix_market_news_source'), 'market_news', ['source'], unique=False)
    op.create_index('ix_market_news_source_date', 'market_news', ['source', 'published_date'], unique=False)
    op.create_table('market_sectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sector_code', sa.String(length=20), nullable=False),
    sa.Column('sector_name', sa.String(length=100), nullable=False),
    sa.Column('sector_name_en', sa.String(length=100), nullable=True),
    sa.Column('parent_code', sa.String(length=20), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('icb_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_sectors'))
    )
    op.create_index(op.f('ix_market_sectors_sector_code'), 'market_sectors', ['sector_code'], unique=True)
    op.create_table('orderbook_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('price_depth', sa.JSON(), nullable=True),
    sa.Column('bid1_price', sa.Float(), nullable=True),
    sa.Column('bid1_volume', sa.BigInteger(), nullable=True),
    sa.Column('bid2_price', sa.Float(), nullable=True),
    sa.Column('bid2_volume', sa.BigInteger(), nullable=True),
    sa.Column('bid3_price', sa.Float(), nullable=True),
    sa.Column('bid3_volume', sa.BigInteger(), nullable=True),
    sa.Column('ask1_price', sa.Float(), nullable=True),
    sa.Column('ask1_volume', sa.BigInteger(), nullable=True),
    sa.Column('ask2_price', sa.Float(), nullable=True),
    sa.Column('ask2_volume', sa.BigInteger(), nullable=True),
    sa.Column('ask3_price', sa.Float(), nullable=True),
    sa.Column('ask3_volume', sa.BigInteger(), nullable=True),
    sa.Column('total_bid_volume', sa.BigInteger(), nullable=True),
    sa.Column('total_ask_volume', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orderbook_snapshots'))
    )
    op.create_index(op.f('ix_orderbook_snapshots_snapshot_time'), 'orderbook_snapshots', ['snapshot_time'], unique=False)
    op.create_index(op.f('ix_orderbook_snapshots_symbol'), 'orderbook_snapshots', ['symbol'], unique=False)
    op.create_index('ix_orderbook_symbol_time', 'orderbook_snapshots', ['symbol', 'snapshot_time'], unique=False)
    op.create_table('sector_performance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sector_code', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('avg_change_pct', sa.Float(), nullable=True),
    sa.Column('total_volume', sa.BigInteger(), nullable=True),
    sa.Column('avg_volume', sa.BigInteger(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('total_market_cap', sa.Float(), nullable=True),
    sa.Column('top_gainer_symbol', sa.String(length=10), nullable=True),
    sa.Column('top_gainer_change', sa.Float(), nullable=True),
    sa.Column('top_loser_symbol', sa.String(length=10), nullable=True),
    sa.Column('top_loser_change', sa.Float(), nullable=True),
    sa.Column('advance_count', sa.Integer(), nullable=True),
    sa.Column('decline_count', sa.Integer(), nullable=True),
    sa.Column('unchanged_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sector_performance')),
    sa.UniqueConstraint('sector_code', 'trade_date', name='uq_sector_perf_code_date')
    )
    op.create_index('ix_sector_perf_date', 'sector_performance', ['trade_date'], unique=False)
    op.create_index(op.f('ix_sector_performance_sector_code'), 'sector_performance', ['sector_code'], unique=False)
    op.create_index(op.f('ix_sector_performance_trade_date'), 'sector_performance', ['trade_date'], unique=False)
    op.create_table('subsidiaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('subsidiary_name', sa.String(length=255), nullable=False),
    sa.Column('subsidiary_symbol', sa.String(length=10), nullable=True),
    sa.Column('ownership_pct', sa.Float(), nullable=True),
    sa.Column('charter_capital', sa.Float(), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subsidiaries'))
    )
    op.create_index(op.f('ix_subsidiaries_symbol'), 'subsidiaries', ['symbol'], unique=False)
    op.create_index('ix_subsidiary_symbol', 'subsidiaries', ['symbol'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('calc_date', sa.Date(), nullable=False),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('ema_12', sa.Float(), nullable=True),
    sa.Column('ema_26', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('stoch_k', sa.Float(), nullable=True),
    sa.Column('stoch_d', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_hist', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_middle', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('obv', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_indicators')),
    sa.UniqueConstraint('symbol', 'calc_date', name='uq_technical_indicator_symbol_date')
    )
    op.create_index('ix_ta_symbol_date', 'technical_indicators', ['symbol', 'calc_date'], unique=False)
    op.create_index(op.f('ix_technical_indicators_symbol'), 'technical_indicators', ['symbol'], unique=False)
    op.alter_column('balance_sheets', 'period_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('balance_sheets', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('balance_sheets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('balance_sheets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_balance_sheets_fiscal_year'), 'balance_sheets', ['fiscal_year'], unique=False)
    op.alter_column('cash_flows', 'period_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('cash_flows', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('cash_flows', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('cash_flows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_cash_flows_fiscal_year'), 'cash_flows', ['fiscal_year'], unique=False)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('uq_companies_symbol'), 'companies', type_='unique')
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    op.alter_column('dashboard_widgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('dashboard_widgets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('income_statements', 'period_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('income_statements', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('income_statements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('income_statements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_income_statements_fiscal_year'), 'income_statements', ['fiscal_year'], unique=False)
    op.alter_column('officers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('officers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('screener_snapshots', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('screener_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_screener_snapshots_industry'), 'screener_snapshots', ['industry'], unique=False)
    op.alter_column('shareholders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shareholders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('stock_indices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_stock_indices_time'), 'stock_indices', ['time'], unique=False)
    op.alter_column('stock_prices', 'interval',
               existing_type=sa.VARCHAR(length=5),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_prices', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('stocks', 'exchange',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stocks', 'is_active',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stocks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('stocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('uq_stocks_symbol'), 'stocks', type_='unique')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.alter_column('user_dashboards', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_dashboards', 'is_default',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('user_dashboards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_dashboards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_dashboards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_dashboards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_dashboards', 'is_default',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('user_dashboards', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               server_default=sa.text("'anonymous'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=False)
    op.create_unique_constraint(op.f('uq_stocks_symbol'), 'stocks', ['symbol'], postgresql_nulls_not_distinct=False)
    op.alter_column('stocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('stocks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('stocks', 'is_active',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('stocks', 'exchange',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'HOSE'::character varying"),
               existing_nullable=False)
    op.alter_column('stock_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('stock_prices', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'vnstock'::character varying"),
               existing_nullable=False)
    op.alter_column('stock_prices', 'interval',
               existing_type=sa.VARCHAR(length=5),
               server_default=sa.text("'1D'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_stock_indices_time'), table_name='stock_indices')
    op.alter_column('stock_indices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shareholders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shareholders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_screener_snapshots_industry'), table_name='screener_snapshots')
    op.alter_column('screener_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('screener_snapshots', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'vnstock'::character varying"),
               existing_nullable=False)
    op.alter_column('officers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('officers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_income_statements_fiscal_year'), table_name='income_statements')
    op.alter_column('income_statements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('income_statements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('income_statements', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'vnstock'::character varying"),
               existing_nullable=False)
    op.alter_column('income_statements', 'period_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'year'::character varying"),
               existing_nullable=False)
    op.alter_column('dashboard_widgets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('dashboard_widgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=False)
    op.create_unique_constraint(op.f('uq_companies_symbol'), 'companies', ['symbol'], postgresql_nulls_not_distinct=False)
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_cash_flows_fiscal_year'), table_name='cash_flows')
    op.alter_column('cash_flows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cash_flows', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cash_flows', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'vnstock'::character varying"),
               existing_nullable=False)
    op.alter_column('cash_flows', 'period_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'year'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_balance_sheets_fiscal_year'), table_name='balance_sheets')
    op.alter_column('balance_sheets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('balance_sheets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('balance_sheets', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'vnstock'::character varying"),
               existing_nullable=False)
    op.alter_column('balance_sheets', 'period_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'year'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_technical_indicators_symbol'), table_name='technical_indicators')
    op.drop_index('ix_ta_symbol_date', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index('ix_subsidiary_symbol', table_name='subsidiaries')
    op.drop_index(op.f('ix_subsidiaries_symbol'), table_name='subsidiaries')
    op.drop_table('subsidiaries')
    op.drop_index(op.f('ix_sector_performance_trade_date'), table_name='sector_performance')
    op.drop_index(op.f('ix_sector_performance_sector_code'), table_name='sector_performance')
    op.drop_index('ix_sector_perf_date', table_name='sector_performance')
    op.drop_table('sector_performance')
    op.drop_index('ix_orderbook_symbol_time', table_name='orderbook_snapshots')
    op.drop_index(op.f('ix_orderbook_snapshots_symbol'), table_name='orderbook_snapshots')
    op.drop_index(op.f('ix_orderbook_snapshots_snapshot_time'), table_name='orderbook_snapshots')
    op.drop_table('orderbook_snapshots')
    op.drop_index(op.f('ix_market_sectors_sector_code'), table_name='market_sectors')
    op.drop_table('market_sectors')
    op.drop_index('ix_market_news_source_date', table_name='market_news')
    op.drop_index(op.f('ix_market_news_source'), table_name='market_news')
    op.drop_index(op.f('ix_market_news_sentiment'), table_name='market_news')
    op.drop_index(op.f('ix_market_news_related_symbols'), table_name='market_news')
    op.drop_index(op.f('ix_market_news_published_date'), table_name='market_news')
    op.drop_index('ix_market_news_published', table_name='market_news')
    op.drop_index(op.f('ix_market_news_is_processed'), table_name='market_news')
    op.drop_table('market_news')
    op.drop_index(op.f('ix_intraday_trades_trade_time'), table_name='intraday_trades')
    op.drop_index(op.f('ix_intraday_trades_symbol'), table_name='intraday_trades')
    op.drop_index('ix_intraday_time', table_name='intraday_trades')
    op.drop_index('ix_intraday_symbol_time', table_name='intraday_trades')
    op.drop_table('intraday_trades')
    op.drop_index('ix_insider_symbol_date', table_name='insider_deals')
    op.drop_index(op.f('ix_insider_deals_symbol'), table_name='insider_deals')
    op.drop_index(op.f('ix_insider_deals_announce_date'), table_name='insider_deals')
    op.drop_table('insider_deals')
    op.drop_index(op.f('ix_foreign_trading_trade_date'), table_name='foreign_trading')
    op.drop_index(op.f('ix_foreign_trading_symbol'), table_name='foreign_trading')
    op.drop_index('ix_foreign_symbol_date', table_name='foreign_trading')
    op.drop_table('foreign_trading')
    op.drop_index('ix_ratio_symbol_year', table_name='financial_ratios')
    op.drop_index(op.f('ix_financial_ratios_symbol'), table_name='financial_ratios')
    op.drop_index(op.f('ix_financial_ratios_fiscal_year'), table_name='financial_ratios')
    op.drop_table('financial_ratios')
    op.drop_index(op.f('ix_dividends_symbol'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_exercise_date'), table_name='dividends')
    op.drop_index('ix_dividend_symbol_date', table_name='dividends')
    op.drop_table('dividends')
    op.drop_index('ix_news_symbol_published', table_name='company_news')
    op.drop_index(op.f('ix_company_news_symbol'), table_name='company_news')
    op.drop_index(op.f('ix_company_news_published_date'), table_name='company_news')
    op.drop_table('company_news')
    op.drop_index('ix_event_type_date', table_name='company_events')
    op.drop_index('ix_event_symbol_date', table_name='company_events')
    op.drop_index(op.f('ix_company_events_symbol'), table_name='company_events')
    op.drop_index(op.f('ix_company_events_event_type'), table_name='company_events')
    op.drop_index(op.f('ix_company_events_event_date'), table_name='company_events')
    op.drop_table('company_events')
    # ### end Alembic commands ###
