"""Sync schema and add indexes

Revision ID: 202c5b1127fc
Revises: 9abd9cdc70b6
Create Date: 2026-01-19 21:57:21.654546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202c5b1127fc'
down_revision: Union[str, None] = '9abd9cdc70b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('block_trade_threshold', sa.Float(), nullable=False),
    sa.Column('enable_insider_buy_alerts', sa.Boolean(), nullable=False),
    sa.Column('enable_insider_sell_alerts', sa.Boolean(), nullable=False),
    sa.Column('enable_ownership_change_alerts', sa.Boolean(), nullable=False),
    sa.Column('ownership_change_threshold', sa.Float(), nullable=False),
    sa.Column('enable_browser_notifications', sa.Boolean(), nullable=False),
    sa.Column('enable_email_notifications', sa.Boolean(), nullable=False),
    sa.Column('enable_sound_alerts', sa.Boolean(), nullable=False),
    sa.Column('notification_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_settings'))
    )
    with op.batch_alter_table('alert_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_settings_user_id'), ['user_id'], unique=True)

    op.create_table('block_trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='tradeside'), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('trade_time', sa.DateTime(), nullable=False),
    sa.Column('counterparty', sa.String(length=100), nullable=True),
    sa.Column('is_foreign', sa.Boolean(), nullable=False),
    sa.Column('is_proprietary', sa.Boolean(), nullable=False),
    sa.Column('avg_volume_20d', sa.BigInteger(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_block_trades'))
    )
    with op.batch_alter_table('block_trades', schema=None) as batch_op:
        batch_op.create_index('ix_block_symbol_time', ['symbol', 'trade_time'], unique=False)
        batch_op.create_index('ix_block_time', ['trade_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_trades_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_trades_trade_time'), ['trade_time'], unique=False)
        batch_op.create_index('ix_block_value', ['value'], unique=False)

    op.create_table('insider_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.Enum('INSIDER_BUY', 'INSIDER_SELL', 'BLOCK_TRADE', 'OWNERSHIP_CHANGE', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='alertseverity'), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('insider_deal_id', sa.BigInteger(), nullable=True),
    sa.Column('block_trade_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insider_alerts'))
    )
    with op.batch_alter_table('insider_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alert_symbol_time', ['symbol', 'timestamp'], unique=False)
        batch_op.create_index('ix_alert_type_time', ['alert_type', 'timestamp'], unique=False)
        batch_op.create_index('ix_alert_user_read', ['user_id', 'read'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_alerts_read'), ['read'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_alerts_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_alerts_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('sync_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_status'))
    )
    with op.batch_alter_table('sync_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_status_sync_type'), ['sync_type'], unique=False)

    with op.batch_alter_table('balance_sheets', schema=None) as batch_op:
        batch_op.alter_column('period_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_balance_sheets_fiscal_year'), ['fiscal_year'], unique=False)

    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.alter_column('period_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_cash_flows_fiscal_year'), ['fiscal_year'], unique=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_companies_symbol'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_companies_symbol'))
        batch_op.create_index(batch_op.f('ix_companies_symbol'), ['symbol'], unique=True)

    with op.batch_alter_table('company_news', schema=None) as batch_op:
        batch_op.create_index('ix_news_source', ['source'], unique=False)

    with op.batch_alter_table('dashboard_widgets', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('income_statements', schema=None) as batch_op:
        batch_op.alter_column('period_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_income_statements_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index('ix_income_stmt_perf', ['symbol', 'net_income'], unique=False)

    with op.batch_alter_table('market_news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_news_sentiment'))
        batch_op.create_index('ix_market_news_sentiment', ['sentiment', 'published_date'], unique=False)

    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('screener_snapshots', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_screener_date_market_cap', ['snapshot_date', 'market_cap'], unique=False)
        batch_op.create_index('ix_screener_market_cap', ['market_cap'], unique=False)
        batch_op.create_index(batch_op.f('ix_screener_snapshots_industry'), ['industry'], unique=False)

    with op.batch_alter_table('shareholders', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('stock_indices', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_stock_indices_time'), ['time'], unique=False)

    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.alter_column('interval',
               existing_type=sa.VARCHAR(length=5),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_stock_price_date_only', ['time'], unique=False)
        batch_op.create_index('ix_stock_price_perf', ['symbol', 'close'], unique=False)

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('exchange',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_stocks_symbol'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_stocks_symbol'))
        batch_op.create_index(batch_op.f('ix_stocks_symbol'), ['symbol'], unique=True)

    with op.batch_alter_table('user_dashboards', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_default',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_dashboards', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_default',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               server_default=sa.text("'anonymous'"),
               existing_nullable=False)

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_symbol'))
        batch_op.create_index(batch_op.f('ix_stocks_symbol'), ['symbol'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_stocks_symbol'), ['symbol'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=False)
        batch_op.alter_column('exchange',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'HOSE'"),
               existing_nullable=False)

    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_price_perf')
        batch_op.drop_index('ix_stock_price_date_only')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'vnstock'"),
               existing_nullable=False)
        batch_op.alter_column('interval',
               existing_type=sa.VARCHAR(length=5),
               server_default=sa.text("'1D'"),
               existing_nullable=False)

    with op.batch_alter_table('stock_indices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_indices_time'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('shareholders', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('screener_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screener_snapshots_industry'))
        batch_op.drop_index('ix_screener_market_cap')
        batch_op.drop_index('ix_screener_date_market_cap')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'vnstock'"),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('market_news', schema=None) as batch_op:
        batch_op.drop_index('ix_market_news_sentiment')
        batch_op.create_index(batch_op.f('ix_market_news_sentiment'), ['sentiment'], unique=False)

    with op.batch_alter_table('income_statements', schema=None) as batch_op:
        batch_op.drop_index('ix_income_stmt_perf')
        batch_op.drop_index(batch_op.f('ix_income_statements_fiscal_year'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'vnstock'"),
               existing_nullable=False)
        batch_op.alter_column('period_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'year'"),
               existing_nullable=False)

    with op.batch_alter_table('dashboard_widgets', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('company_news', schema=None) as batch_op:
        batch_op.drop_index('ix_news_source')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_symbol'))
        batch_op.create_index(batch_op.f('ix_companies_symbol'), ['symbol'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_companies_symbol'), ['symbol'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_flows_fiscal_year'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'vnstock'"),
               existing_nullable=False)
        batch_op.alter_column('period_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'year'"),
               existing_nullable=False)

    with op.batch_alter_table('balance_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_sheets_fiscal_year'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'vnstock'"),
               existing_nullable=False)
        batch_op.alter_column('period_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'year'"),
               existing_nullable=False)

    with op.batch_alter_table('sync_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_status_sync_type'))

    op.drop_table('sync_status')
    with op.batch_alter_table('insider_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insider_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_insider_alerts_timestamp'))
        batch_op.drop_index(batch_op.f('ix_insider_alerts_symbol'))
        batch_op.drop_index(batch_op.f('ix_insider_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_insider_alerts_read'))
        batch_op.drop_index(batch_op.f('ix_insider_alerts_alert_type'))
        batch_op.drop_index('ix_alert_user_read')
        batch_op.drop_index('ix_alert_type_time')
        batch_op.drop_index('ix_alert_symbol_time')

    op.drop_table('insider_alerts')
    with op.batch_alter_table('block_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_block_value')
        batch_op.drop_index(batch_op.f('ix_block_trades_trade_time'))
        batch_op.drop_index(batch_op.f('ix_block_trades_symbol'))
        batch_op.drop_index('ix_block_time')
        batch_op.drop_index('ix_block_symbol_time')

    op.drop_table('block_trades')
    with op.batch_alter_table('alert_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_settings_user_id'))

    op.drop_table('alert_settings')
    # ### end Alembic commands ###
