#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

APPWRITE_ENV_FILE="${APPWRITE_ENV_FILE:-$ROOT_DIR/deployment/env.oracle}"
MIGRATION_SCHEMA_MAP="${MIGRATION_SCHEMA_MAP:-$ROOT_DIR/scripts/appwrite/schema-map.example.json}"
MIGRATION_STATE_FILE="${MIGRATION_STATE_FILE:-$ROOT_DIR/scripts/appwrite/migration_state.json}"
MIGRATION_BASELINE_OUT="${MIGRATION_BASELINE_OUT:-$ROOT_DIR/scripts/appwrite/supabase_baseline.json}"
MIGRATION_BATCH_SIZE="${MIGRATION_BATCH_SIZE:-300}"
MIGRATION_CONCURRENCY="${MIGRATION_CONCURRENCY:-4}"
MIGRATION_PAGINATION_MODE="${MIGRATION_PAGINATION_MODE:-keyset}"
MIGRATION_RESUME="${MIGRATION_RESUME:-true}"
MIGRATION_SNAPSHOT_UPPER_BOUND="${MIGRATION_SNAPSHOT_UPPER_BOUND:-true}"
MIGRATION_COERCE_ALL_TO_STRING="${MIGRATION_COERCE_ALL_TO_STRING:-true}"
MIGRATION_MAX_ROWS="${MIGRATION_MAX_ROWS:-0}"
MIGRATION_TABLES="${MIGRATION_TABLES:-}"
MIGRATION_DRY_RUN="${MIGRATION_DRY_RUN:-false}"
VERIFY_SOURCE_MODE="${VERIFY_SOURCE_MODE:-baseline}"
ENSURE_TEXTSAFE_ATTRIBUTES="${ENSURE_TEXTSAFE_ATTRIBUTES:-1}"
RUN_READINESS_CHECK="${RUN_READINESS_CHECK:-1}"

is_truthy() {
  case "${1,,}" in
    1|true|yes|on) return 0 ;;
    *) return 1 ;;
  esac
}

if [[ ! -f "$APPWRITE_ENV_FILE" ]]; then
  echo "APPWRITE_ENV_FILE not found: $APPWRITE_ENV_FILE"
  exit 1
fi

if [[ ! -f "$MIGRATION_SCHEMA_MAP" ]]; then
  echo "MIGRATION_SCHEMA_MAP not found: $MIGRATION_SCHEMA_MAP"
  exit 1
fi

if ! command -v node >/dev/null 2>&1; then
  echo "Node.js is required for full Node migration flow. Install Node 22+ and retry."
  exit 1
fi

if ! node -e "require('pg'); require('node-appwrite')" >/dev/null 2>&1; then
  echo "Missing Node dependencies. Run: pnpm add -D pg node-appwrite"
  exit 1
fi

echo "Starting full Node Appwrite migration"
echo "  APPWRITE_ENV_FILE=$APPWRITE_ENV_FILE"
echo "  MIGRATION_SCHEMA_MAP=$MIGRATION_SCHEMA_MAP"
echo "  MIGRATION_TABLES=${MIGRATION_TABLES:-<all mapped tables>}"
echo "  MIGRATION_DRY_RUN=$MIGRATION_DRY_RUN"
echo "  MIGRATION_BATCH_SIZE=$MIGRATION_BATCH_SIZE"
echo "  MIGRATION_CONCURRENCY=$MIGRATION_CONCURRENCY"

APPWRITE_ENV_FILE="$APPWRITE_ENV_FILE" \
MIGRATION_SCHEMA_MAP="$MIGRATION_SCHEMA_MAP" \
node "$ROOT_DIR/scripts/appwrite/check_appwrite_connectivity.mjs"

APPWRITE_ENV_FILE="$APPWRITE_ENV_FILE" \
MIGRATION_SCHEMA_MAP="$MIGRATION_SCHEMA_MAP" \
MIGRATION_BASELINE_OUT="$MIGRATION_BASELINE_OUT" \
node "$ROOT_DIR/scripts/appwrite/export_supabase_baseline.mjs"

APPWRITE_ENV_FILE="$APPWRITE_ENV_FILE" \
MIGRATION_SCHEMA_MAP="$MIGRATION_SCHEMA_MAP" \
MIGRATION_TABLES="$MIGRATION_TABLES" \
node "$ROOT_DIR/scripts/appwrite/ensure_appwrite_collections.mjs"

if is_truthy "$ENSURE_TEXTSAFE_ATTRIBUTES"; then
  APPWRITE_ENV_FILE="$APPWRITE_ENV_FILE" \
  MIGRATION_SCHEMA_MAP="$MIGRATION_SCHEMA_MAP" \
  MIGRATION_TABLES="$MIGRATION_TABLES" \
  node "$ROOT_DIR/scripts/appwrite/ensure_appwrite_attributes_textsafe.mjs"
fi

APPWRITE_ENV_FILE="$APPWRITE_ENV_FILE" \
MIGRATION_SCHEMA_MAP="$MIGRATION_SCHEMA_MAP" \
MIGRATION_STATE_FILE="$MIGRATION_STATE_FILE" \
MIGRATION_TABLES="$MIGRATION_TABLES" \
MIGRATION_DRY_RUN="$MIGRATION_DRY_RUN" \
MIGRATION_PAGINATION_MODE="$MIGRATION_PAGINATION_MODE" \
MIGRATION_RESUME="$MIGRATION_RESUME" \
MIGRATION_SNAPSHOT_UPPER_BOUND="$MIGRATION_SNAPSHOT_UPPER_BOUND" \
MIGRATION_COERCE_ALL_TO_STRING="$MIGRATION_COERCE_ALL_TO_STRING" \
MIGRATION_BATCH_SIZE="$MIGRATION_BATCH_SIZE" \
MIGRATION_CONCURRENCY="$MIGRATION_CONCURRENCY" \
MIGRATION_MAX_ROWS="$MIGRATION_MAX_ROWS" \
node "$ROOT_DIR/scripts/appwrite/migrate_supabase_to_appwrite.mjs"

APPWRITE_ENV_FILE="$APPWRITE_ENV_FILE" \
MIGRATION_SCHEMA_MAP="$MIGRATION_SCHEMA_MAP" \
MIGRATION_TABLES="$MIGRATION_TABLES" \
VERIFY_SOURCE_MODE="$VERIFY_SOURCE_MODE" \
VERIFY_BASELINE_FILE="$MIGRATION_BASELINE_OUT" \
node "$ROOT_DIR/scripts/appwrite/verify_appwrite_counts.mjs"

if is_truthy "$RUN_READINESS_CHECK"; then
  APPWRITE_ENV_FILE="$APPWRITE_ENV_FILE" \
  VERIFY_BASELINE_FILE="$MIGRATION_BASELINE_OUT" \
  node "$ROOT_DIR/scripts/appwrite/check_cutover_readiness.mjs"
fi

echo "Full Node Appwrite migration flow completed"
