#!/usr/bin/env python3
"""Copy hosted Supabase public tables into self-hosted n6v Supabase.

This intentionally avoids pg_dump so it can run from machines that do not have
Postgres 17 client tools installed.
"""

from __future__ import annotations

import argparse
import os
from io import StringIO

import psycopg2
from psycopg2 import sql


def connect(dsn: str):
    return psycopg2.connect(dsn, connect_timeout=20)


def fetch_tables(conn) -> list[str]:
    with conn.cursor() as cur:
        cur.execute(
            """
            select table_name
            from information_schema.tables
            where table_schema = 'public'
              and table_type = 'BASE TABLE'
            order by table_name
            """
        )
        return [row[0] for row in cur.fetchall()]


def create_custom_types(source, target) -> None:
    with source.cursor() as cur:
        cur.execute(
            """
            select t.typname, e.enumlabel
            from pg_type t
            join pg_namespace n on n.oid = t.typnamespace
            join pg_enum e on e.enumtypid = t.oid
            where n.nspname = 'public'
            order by t.typname, e.enumsortorder
            """
        )
        enum_rows = cur.fetchall()

    enums: dict[str, list[str]] = {}
    for type_name, label in enum_rows:
        enums.setdefault(type_name, []).append(label)

    with target.cursor() as cur:
        for type_name, labels in enums.items():
            cur.execute(
                "select 1 from pg_type t join pg_namespace n on n.oid = t.typnamespace where n.nspname = 'public' and t.typname = %s",
                (type_name,),
            )
            if cur.fetchone():
                continue
            cur.execute(
                sql.SQL("create type public.{} as enum ({})").format(
                    sql.Identifier(type_name),
                    sql.SQL(", ").join(sql.Literal(label) for label in labels),
                )
            )
    target.commit()


def fetch_columns(conn, table: str) -> list[dict[str, object]]:
    with conn.cursor() as cur:
        cur.execute(
            """
            select
                a.attname,
                pg_catalog.format_type(a.atttypid, a.atttypmod) as formatted_type,
                a.attnotnull,
                pg_get_expr(ad.adbin, ad.adrelid) as default_value,
                a.attidentity
            from pg_attribute a
            join pg_class c on c.oid = a.attrelid
            join pg_namespace n on n.oid = c.relnamespace
            left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
            where n.nspname = 'public'
              and c.relname = %s
              and a.attnum > 0
              and not a.attisdropped
            order by a.attnum
            """,
            (table,),
        )
        return [
            {
                "name": row[0],
                "type": row[1],
                "not_null": row[2],
                "default": row[3],
                "identity": row[4],
            }
            for row in cur.fetchall()
        ]


def fetch_primary_key(conn, table: str) -> list[str]:
    with conn.cursor() as cur:
        cur.execute(
            """
            select a.attname
            from pg_index i
            join pg_class c on c.oid = i.indrelid
            join pg_namespace n on n.oid = c.relnamespace
            join pg_attribute a on a.attrelid = i.indrelid and a.attnum = any(i.indkey)
            where n.nspname = 'public'
              and c.relname = %s
              and i.indisprimary
            order by array_position(i.indkey, a.attnum)
            """,
            (table,),
        )
        return [row[0] for row in cur.fetchall()]


def create_table(source, target, table: str, drop_existing: bool) -> None:
    columns = fetch_columns(source, table)
    if not columns:
        return

    parts = []
    for column in columns:
        ident = sql.Identifier(str(column["name"]))
        default_value = str(column["default"]) if column["default"] is not None else ""
        if column["identity"] or default_value.startswith("nextval("):
            clause = sql.SQL("{} {} generated by default as identity").format(
                ident,
                sql.SQL(str(column["type"])),
            )
        else:
            clause = sql.SQL("{} {}").format(ident, sql.SQL(str(column["type"])))
            if column["default"] is not None:
                clause += sql.SQL(" default ") + sql.SQL(str(column["default"]))
        if column["not_null"]:
            clause += sql.SQL(" not null")
        parts.append(clause)

    pk = fetch_primary_key(source, table)
    if pk:
        parts.append(
            sql.SQL("primary key ({})").format(
                sql.SQL(", ").join(sql.Identifier(col) for col in pk)
            )
        )

    with target.cursor() as cur:
        if drop_existing:
            cur.execute(sql.SQL("drop table if exists public.{} cascade").format(sql.Identifier(table)))
        cur.execute(
            sql.SQL("create table if not exists public.{} ({})").format(
                sql.Identifier(table),
                sql.SQL(", ").join(parts),
            )
        )
    target.commit()


def copy_table(source, target, table: str, truncate: bool) -> int:
    columns = [str(col["name"]) for col in fetch_columns(source, table)]
    if not columns:
        return 0

    quoted_table = sql.Identifier("public", table).as_string(source)
    quoted_cols = ", ".join(sql.Identifier(col).as_string(source) for col in columns)
    buffer = StringIO()

    with source.cursor() as cur:
        cur.copy_expert(f"copy {quoted_table} ({quoted_cols}) to stdout with csv", buffer)

    buffer.seek(0)
    row_count = 0 if not buffer.getvalue() else buffer.getvalue().count("\n")

    with target.cursor() as cur:
        if truncate:
            cur.execute(sql.SQL("truncate table public.{} cascade").format(sql.Identifier(table)))
        target_table = sql.Identifier("public", table).as_string(target)
        target_cols = ", ".join(sql.Identifier(col).as_string(target) for col in columns)
        cur.copy_expert(f"copy {target_table} ({target_cols}) from stdin with csv", buffer)
    target.commit()
    return row_count


def reset_sequences(target) -> None:
    with target.cursor() as cur:
        cur.execute(
            """
            select schemaname, sequencename
            from pg_sequences
            where schemaname = 'public'
            order by sequencename
            """
        )
        sequences = cur.fetchall()
        for schema, sequence in sequences:
            cur.execute(
                sql.SQL("select setval({seq}::regclass, coalesce((select max(id) from public.{table}), 1), true)").format(
                    seq=sql.Literal(f"{schema}.{sequence}"),
                    table=sql.Identifier(sequence.removesuffix("_id_seq")),
                )
            )
    target.commit()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Copy hosted Supabase public tables to n6v self-hosted Supabase")
    parser.add_argument("--source-dsn", default=os.getenv("SOURCE_DATABASE_URL", ""))
    parser.add_argument("--target-dsn", default=os.getenv("TARGET_DATABASE_URL", ""))
    parser.add_argument("--tables", default="", help="Comma-separated table allowlist")
    parser.add_argument("--drop-existing", action="store_true")
    parser.add_argument("--truncate", action="store_true")
    parser.add_argument("--skip-sequences", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not args.source_dsn or not args.target_dsn:
        raise SystemExit("--source-dsn and --target-dsn are required")

    source = connect(args.source_dsn)
    target = connect(args.target_dsn)
    allowlist = {item.strip() for item in args.tables.split(",") if item.strip()}
    tables = [table for table in fetch_tables(source) if not allowlist or table in allowlist]
    print(f"Migrating {len(tables)} public tables")

    with target.cursor() as cur:
        cur.execute("create extension if not exists pgcrypto")
        cur.execute("create extension if not exists \"uuid-ossp\"")
    target.commit()
    create_custom_types(source, target)

    for table in tables:
        create_table(source, target, table, drop_existing=args.drop_existing)
        rows = copy_table(source, target, table, truncate=args.truncate)
        print(f"{table}: {rows} rows")

    if not args.skip_sequences:
        try:
            reset_sequences(target)
        except Exception as exc:  # noqa: BLE001
            target.rollback()
            print(f"sequence reset skipped: {exc}")

    source.close()
    target.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
